blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Report
    url: https://github.com/darkreader/darkreader/security/policy
    about: Review our security policy for more details.
  - name: Questions
    url: https://github.com/darkreader/darkreader/discussions
    about: Ask a question about Dark Reader.
