export enum MessageType {
    UI_GET_DATA = 0,
    UI_GET_ACTIVE_TAB_INFO = 1,
    UI_SUBSCRIBE_TO_CHANGES = 2,
    UI_UNSUBSCRIBE_FROM_CHANGES = 3,
    UI_CHANGE_SETTINGS = 4,
    UI_SET_THEME = 5,
    UI_SET_SHORTCUT = 6,
    UI_TOGGLE_URL = 7,
    UI_MARK_NEWS_AS_READ = 8,
    UI_LOAD_CONFIG = 9,
    UI_APPLY_DEV_DYNAMIC_THEME_FIXES = 10,
    UI_RESET_DEV_DYNAMIC_THEME_FIXES = 11,
    UI_APPLY_DEV_INVERSION_FIXES = 12,
    UI_RESET_DEV_INVERSION_FIXES = 13,
    UI_APPLY_DEV_STATIC_THEMES = 14,
    UI_RESET_DEV_STATIC_THEMES = 15,

    BACKGROUND_CHANGES = 16,
    BACKGROUND_ADD_CSS_FILTER = 17,
    BACKGROUND_ADD_STATIC_THEME = 18,
    BACKGROUND_ADD_SVG_FILTER = 19,
    BACKGROUND_ADD_DYNAMIC_THEME = 20,
    BACKGROUND_EXPORT_CSS = 21,
    BACKGROUND_UNSUPPORTED_SENDER = 22,
    BACKGROUND_CLEAN_UP = 23,
    BACKGROUND_RELOAD = 24,
    BACKGROUND_FETCH_RESPONSE = 25,

    CS_COLOR_SCHEME_CHANGE = 26,
    CS_FRAME_CONNECT = 27,
    CS_FRAME_FORGET = 28,
    CS_FRAME_FREEZE = 29,
    CS_FRAME_RESUME = 30,
    CS_EXPORT_CSS_RESPONSE = 31,
    UI_SAVE_FILE = 32,
    UI_REQUEST_EXPORT_CSS = 33,
    CS_FETCH = 34,
}

// This map exists only for debugging convenience and is not used in the final build output.
export const MessageTypeDescriptions = {
    [MessageType.UI_GET_DATA]: 'ui-get-data',
    [MessageType.UI_GET_ACTIVE_TAB_INFO]: 'ui-get-active-tab-info',
    [MessageType.UI_SUBSCRIBE_TO_CHANGES]: 'subscribe-to-changes',
    [MessageType.UI_UNSUBSCRIBE_FROM_CHANGES]: 'unsubscribe-from-changes',
    [MessageType.UI_CHANGE_SETTINGS]: 'change-settings',
    [MessageType.UI_SET_THEME]: 'set-theme',
    [MessageType.UI_SET_SHORTCUT]: 'set-shortcut',
    [MessageType.UI_TOGGLE_URL]: 'toggle-url',
    [MessageType.UI_MARK_NEWS_AS_READ]: 'mark-news-as-read',
    [MessageType.UI_LOAD_CONFIG]: 'load-config',
    [MessageType.UI_APPLY_DEV_DYNAMIC_THEME_FIXES]: 'apply-dev-dynamic-theme-fixes',
    [MessageType.UI_RESET_DEV_DYNAMIC_THEME_FIXES]: 'reset-dev-dynamic-theme-fixes',
    [MessageType.UI_APPLY_DEV_INVERSION_FIXES]: 'apply-dev-inversion-fixes',
    [MessageType.UI_RESET_DEV_INVERSION_FIXES]: 'reset-dev-inversion-fixes',
    [MessageType.UI_APPLY_DEV_STATIC_THEMES]: 'apply-dev-static-themes',
    [MessageType.UI_RESET_DEV_STATIC_THEMES]: 'reset-dev-static-themes',
    [MessageType.CS_EXPORT_CSS_RESPONSE]: 'export-css-response',

    [MessageType.BACKGROUND_CHANGES]: 'changes',
    [MessageType.BACKGROUND_ADD_CSS_FILTER]: 'add-css-filter',
    [MessageType.BACKGROUND_ADD_STATIC_THEME]: 'add-static-theme',
    [MessageType.BACKGROUND_ADD_SVG_FILTER]: 'add-svg-filter',
    [MessageType.BACKGROUND_ADD_DYNAMIC_THEME]: 'add-dynamic-theme',
    [MessageType.BACKGROUND_EXPORT_CSS]: 'export-css',
    [MessageType.BACKGROUND_UNSUPPORTED_SENDER]: 'unsupported-sender',
    [MessageType.BACKGROUND_CLEAN_UP]: 'clean-up',
    [MessageType.BACKGROUND_RELOAD]: 'reload',
    [MessageType.BACKGROUND_FETCH_RESPONSE]: 'fetch-response',

    [MessageType.CS_COLOR_SCHEME_CHANGE]: 'color-scheme-change',
    [MessageType.CS_FRAME_CONNECT]: 'frame-connect',
    [MessageType.CS_FRAME_FORGET]: 'frame-forget',
    [MessageType.CS_FRAME_FREEZE]: 'frame-freeze',
    [MessageType.CS_FRAME_RESUME]: 'frame-resume',
    [MessageType.UI_SAVE_FILE]: 'save-file',
    [MessageType.UI_REQUEST_EXPORT_CSS]: 'request-export-css',
    [MessageType.CS_FETCH]: 'fetch'
};
