export enum MessageType {
    UI_ENABLE,
    UI_DISABLE,
    UI_GET_DATA,
    UI_GET_ACTIVE_TAB_INFO,
    UI_SUBSCRIBE_TO_CHANGES,
    UI_UNSUBSCRIBE_FROM_CHANGES,
    UI_CHANGE_SETTINGS,
    UI_SET_THEME,
    UI_SET_SHORTCUT,
    UI_TOGGLE_URL,
    UI_MARK_NEWS_AS_READ,
    UI_LOAD_CONFIG,
    UI_APPLY_DEV_DYNAMIC_THEME_FIXES,
    UI_RESET_DEV_DYNAMIC_THEME_FIXES,
    UI_APPLY_DEV_INVERSION_FIXES,
    UI_RESET_DEV_INVERSION_FIXES,
    UI_APPLY_DEV_STATIC_THEMES,
    UI_RESET_DEV_STATIC_THEMES,

    BACKGROUND_CHANGES,
    BACKGROUND_ADD_CSS_FILTER,
    BACKGROUND_ADD_STATIC_THEME,
    BACKGROUND_ADD_SVG_FILTER,
    BACKGROUND_ADD_DYNAMIC_THEME,
    BACKGROUND_EXPORT_CSS,
    BACKGROUND_UNSUPPORTED_SENDER,
    BACKGROUND_CLEAN_UP,
    BACKGROUND_RELOAD,
    BACKGROUND_FETCH_RESPONSE,

    CS_COLOR_SCHEME_CHANGE,
    CS_FRAME_CONNECT,
    CS_FRAME_FORGET,
    CS_FRAME_FREEZE,
    CS_FRAME_RESUME,
    CS_EXPORT_CSS_RESPONSE,
    UI_SAVE_FILE,
    UI_REQUEST_EXPORT_CSS,
    CS_FETCH,
}

// This map exists only for debugging convenience and is not used in the final build output.
export const MessageTypeDescriptions = {
    [MessageType.UI_ENABLE]: 'enable',
    [MessageType.UI_DISABLE]: 'disable',
    [MessageType.UI_GET_DATA]: 'ui-get-data',
    [MessageType.UI_GET_ACTIVE_TAB_INFO]: 'ui-get-active-tab-info',
    [MessageType.UI_SUBSCRIBE_TO_CHANGES]: 'subscribe-to-changes',
    [MessageType.UI_UNSUBSCRIBE_FROM_CHANGES]: 'unsubscribe-from-changes',
    [MessageType.UI_CHANGE_SETTINGS]: 'change-settings',
    [MessageType.UI_SET_THEME]: 'set-theme',
    [MessageType.UI_SET_SHORTCUT]: 'set-shortcut',
    [MessageType.UI_TOGGLE_URL]: 'toggle-url',
    [MessageType.UI_MARK_NEWS_AS_READ]: 'mark-news-as-read',
    [MessageType.UI_LOAD_CONFIG]: 'load-config',
    [MessageType.UI_APPLY_DEV_DYNAMIC_THEME_FIXES]: 'apply-dev-dynamic-theme-fixes',
    [MessageType.UI_RESET_DEV_DYNAMIC_THEME_FIXES]: 'reset-dev-dynamic-theme-fixes',
    [MessageType.UI_APPLY_DEV_INVERSION_FIXES]: 'apply-dev-inversion-fixes',
    [MessageType.UI_RESET_DEV_INVERSION_FIXES]: 'reset-dev-inversion-fixes',
    [MessageType.UI_APPLY_DEV_STATIC_THEMES]: 'apply-dev-static-themes',
    [MessageType.UI_RESET_DEV_STATIC_THEMES]: 'reset-dev-static-themes',
    [MessageType.CS_EXPORT_CSS_RESPONSE]: 'export-css-response',

    [MessageType.BACKGROUND_CHANGES]: 'changes',
    [MessageType.BACKGROUND_ADD_CSS_FILTER]: 'add-css-filter',
    [MessageType.BACKGROUND_ADD_STATIC_THEME]: 'add-static-theme',
    [MessageType.BACKGROUND_ADD_SVG_FILTER]: 'add-svg-filter',
    [MessageType.BACKGROUND_ADD_DYNAMIC_THEME]: 'add-dynamic-theme',
    [MessageType.BACKGROUND_EXPORT_CSS]: 'export-css',
    [MessageType.BACKGROUND_UNSUPPORTED_SENDER]: 'unsupported-sender',
    [MessageType.BACKGROUND_CLEAN_UP]: 'clean-up',
    [MessageType.BACKGROUND_RELOAD]: 'reload',
    [MessageType.BACKGROUND_FETCH_RESPONSE]: 'fetch-response',

    [MessageType.CS_COLOR_SCHEME_CHANGE]: 'color-scheme-change',
    [MessageType.CS_FRAME_CONNECT]: 'frame-connect',
    [MessageType.CS_FRAME_FORGET]: 'frame-forget',
    [MessageType.CS_FRAME_FREEZE]: 'frame-freeze',
    [MessageType.CS_FRAME_RESUME]: 'frame-resume',
    [MessageType.UI_SAVE_FILE]: 'save-file',
    [MessageType.UI_REQUEST_EXPORT_CSS]: 'request-export-css',
    [MessageType.CS_FETCH]: 'fetch'
};
